[package]
name = "mafia-game-lib"
version.workspace = true
authors.workspace = true
description.workspace = true
edition.workspace = true

[dependencies]
serde = { version = "1.0.219", features = ["alloc", "derive", "rc"] }
uuid = { version = "1.16", features = ["default", "serde", "v4"] }
